# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SquareRootFactor = channel.unary_unary(
        '/Calculator/SquareRootFactor',
        request_serializer=calculator__pb2.NumberRequest.SerializeToString,
        response_deserializer=calculator__pb2.NumberReply.FromString,
        )
    self.Mult = channel.unary_unary(
        '/Calculator/Mult',
        request_serializer=calculator__pb2.NumberRequest.SerializeToString,
        response_deserializer=calculator__pb2.MultAll.FromString,
        )


class CalculatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SquareRootFactor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Mult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SquareRootFactor': grpc.unary_unary_rpc_method_handler(
          servicer.SquareRootFactor,
          request_deserializer=calculator__pb2.NumberRequest.FromString,
          response_serializer=calculator__pb2.NumberReply.SerializeToString,
      ),
      'Mult': grpc.unary_unary_rpc_method_handler(
          servicer.Mult,
          request_deserializer=calculator__pb2.NumberRequest.FromString,
          response_serializer=calculator__pb2.MultAll.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
