# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\".\n\rNumberRequest\x12\r\n\x05value\x18\x01 \x01(\x02\x12\x0e\n\x06\x66\x61\x63tor\x18\x02 \x01(\x05\"\x1c\n\x0bNumberReply\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1c\n\x07MultAll\x12\x11\n\tmultValue\x18\x01 \x01(\x02\x32\x64\n\nCalculator\x12\x32\n\x10SquareRootFactor\x12\x0e.NumberRequest\x1a\x0c.NumberReply\"\x00\x12\"\n\x04Mult\x12\x0e.NumberRequest\x1a\x08.MultAll\"\x00\x62\x06proto3')
)




_NUMBERREQUEST = _descriptor.Descriptor(
  name='NumberRequest',
  full_name='NumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='NumberRequest.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='factor', full_name='NumberRequest.factor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=66,
)


_NUMBERREPLY = _descriptor.Descriptor(
  name='NumberReply',
  full_name='NumberReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='NumberReply.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=96,
)


_MULTALL = _descriptor.Descriptor(
  name='MultAll',
  full_name='MultAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='multValue', full_name='MultAll.multValue', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['NumberRequest'] = _NUMBERREQUEST
DESCRIPTOR.message_types_by_name['NumberReply'] = _NUMBERREPLY
DESCRIPTOR.message_types_by_name['MultAll'] = _MULTALL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NumberRequest = _reflection.GeneratedProtocolMessageType('NumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:NumberRequest)
  })
_sym_db.RegisterMessage(NumberRequest)

NumberReply = _reflection.GeneratedProtocolMessageType('NumberReply', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERREPLY,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:NumberReply)
  })
_sym_db.RegisterMessage(NumberReply)

MultAll = _reflection.GeneratedProtocolMessageType('MultAll', (_message.Message,), {
  'DESCRIPTOR' : _MULTALL,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:MultAll)
  })
_sym_db.RegisterMessage(MultAll)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=128,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='SquareRootFactor',
    full_name='Calculator.SquareRootFactor',
    index=0,
    containing_service=None,
    input_type=_NUMBERREQUEST,
    output_type=_NUMBERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Mult',
    full_name='Calculator.Mult',
    index=1,
    containing_service=None,
    input_type=_NUMBERREQUEST,
    output_type=_MULTALL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
